{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle-plugin",
    "version": "0.1.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.24.jar",
          "url": "gradle-plugin-0.1.24.jar",
          "size": 530124,
          "sha512": "773c45988ce4ce9a0c927992b83506372d8ab39e279b530a46fa6dc9a3f428ac9e663afe5a4bd4cc62a52e0c953c72e6829a66dd04c91af0e9f42c521064b187",
          "sha256": "3a7a5b9b259d1f6a1641c445e04adf7c300d9fd342aef2431c2a0925637f43f8",
          "sha1": "7771418218545d27a0e9afa25ee9badc84431f0b",
          "md5": "879c918ea107c7a02d8af625d30a8f6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.thetransactioncompany",
          "module": "jsonrpc2-client",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.24.jar",
          "url": "gradle-plugin-0.1.24.jar",
          "size": 530124,
          "sha512": "773c45988ce4ce9a0c927992b83506372d8ab39e279b530a46fa6dc9a3f428ac9e663afe5a4bd4cc62a52e0c953c72e6829a66dd04c91af0e9f42c521064b187",
          "sha256": "3a7a5b9b259d1f6a1641c445e04adf7c300d9fd342aef2431c2a0925637f43f8",
          "sha1": "7771418218545d27a0e9afa25ee9badc84431f0b",
          "md5": "879c918ea107c7a02d8af625d30a8f6c"
        }
      ]
    }
  ]
}
