{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle-plugin",
    "version": "0.1.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.22.jar",
          "url": "gradle-plugin-0.1.22.jar",
          "size": 508177,
          "sha512": "6ccf2efb8b72327f8799358e68183295a80a553eb34d6cc64fc23de90768ed0c912a45d15e50a89384eca9396f571eaf3fac2079c2ddcc89d918a90eae7b2693",
          "sha256": "294ab2ba4ad9ab40587062691e3981887e8698abe26ac01e6d58a55ef78359bb",
          "sha1": "0d95f27bfaf389e32d0249641c39f41b98895d4a",
          "md5": "53ae8780e5ce2441ad6a7068e1c49960"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.thetransactioncompany",
          "module": "jsonrpc2-client",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.22.jar",
          "url": "gradle-plugin-0.1.22.jar",
          "size": 508177,
          "sha512": "6ccf2efb8b72327f8799358e68183295a80a553eb34d6cc64fc23de90768ed0c912a45d15e50a89384eca9396f571eaf3fac2079c2ddcc89d918a90eae7b2693",
          "sha256": "294ab2ba4ad9ab40587062691e3981887e8698abe26ac01e6d58a55ef78359bb",
          "sha1": "0d95f27bfaf389e32d0249641c39f41b98895d4a",
          "md5": "53ae8780e5ce2441ad6a7068e1c49960"
        }
      ]
    }
  ]
}
