{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle-plugin",
    "version": "0.1.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.26.jar",
          "url": "gradle-plugin-0.1.26.jar",
          "size": 539816,
          "sha512": "119b1f6e6428d1e117bd0bf16ef902cdd163443e97c02e2c2c7106346cde0fff171281f8d3b173b930da563729a88934408e495722fa6808b2a32c7e3e69eebc",
          "sha256": "2731d5db9a9633895a4b27637e896e8f30e5bf7044763e800c9474a674ab339a",
          "sha1": "992fc9a60a179afce66ea39ac601b1c1bee9490a",
          "md5": "8287837acfde60a921362bced2a2e08e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.thetransactioncompany",
          "module": "jsonrpc2-client",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.26.jar",
          "url": "gradle-plugin-0.1.26.jar",
          "size": 539816,
          "sha512": "119b1f6e6428d1e117bd0bf16ef902cdd163443e97c02e2c2c7106346cde0fff171281f8d3b173b930da563729a88934408e495722fa6808b2a32c7e3e69eebc",
          "sha256": "2731d5db9a9633895a4b27637e896e8f30e5bf7044763e800c9474a674ab339a",
          "sha1": "992fc9a60a179afce66ea39ac601b1c1bee9490a",
          "md5": "8287837acfde60a921362bced2a2e08e"
        }
      ]
    }
  ]
}
