{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle-plugin",
    "version": "0.1.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.25.jar",
          "url": "gradle-plugin-0.1.25.jar",
          "size": 537797,
          "sha512": "854776f868c93c24dc2da2dd81dd0d177cff659b09b6a976bca4710d5989d9e3d58ae07acdfe5bafeec0bd3b2296aed1a2b88e1006e9f7e0bd113c994a28c77b",
          "sha256": "6eca724192c3dcba871a07f949f4b03c7ff7f8ffb67f8695dea05fde1ef713a4",
          "sha1": "811d048b8751343afa1c408fff811874544c4a7e",
          "md5": "bc56bd8e0b75af2664140cffaa4a4046"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.thetransactioncompany",
          "module": "jsonrpc2-client",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.25.jar",
          "url": "gradle-plugin-0.1.25.jar",
          "size": 537797,
          "sha512": "854776f868c93c24dc2da2dd81dd0d177cff659b09b6a976bca4710d5989d9e3d58ae07acdfe5bafeec0bd3b2296aed1a2b88e1006e9f7e0bd113c994a28c77b",
          "sha256": "6eca724192c3dcba871a07f949f4b03c7ff7f8ffb67f8695dea05fde1ef713a4",
          "sha1": "811d048b8751343afa1c408fff811874544c4a7e",
          "md5": "bc56bd8e0b75af2664140cffaa4a4046"
        }
      ]
    }
  ]
}
