{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle-plugin",
    "version": "0.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.21.jar",
          "url": "gradle-plugin-0.1.21.jar",
          "size": 508654,
          "sha512": "f44c2b1143e8b24de9b332892462f9ec0fa61d639fa538f1afdd9a21278b29dcc33c47b5a290ab165c93bdc9d3ae9b5fdd7dc6b7171ffb5965959367e54ca609",
          "sha256": "5103ff8d025a120897a151e3f3bb1b4946f057b3ee285630f31f4bceb3f8d36a",
          "sha1": "68a22ddd7ef2fee9b79b52d9a80d19884dbc95b0",
          "md5": "362e8f89145c50393a57177fe8634ed3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.thetransactioncompany",
          "module": "jsonrpc2-client",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.21.jar",
          "url": "gradle-plugin-0.1.21.jar",
          "size": 508654,
          "sha512": "f44c2b1143e8b24de9b332892462f9ec0fa61d639fa538f1afdd9a21278b29dcc33c47b5a290ab165c93bdc9d3ae9b5fdd7dc6b7171ffb5965959367e54ca609",
          "sha256": "5103ff8d025a120897a151e3f3bb1b4946f057b3ee285630f31f4bceb3f8d36a",
          "sha1": "68a22ddd7ef2fee9b79b52d9a80d19884dbc95b0",
          "md5": "362e8f89145c50393a57177fe8634ed3"
        }
      ]
    }
  ]
}
