{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle-plugin",
    "version": "0.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.18.jar",
          "url": "gradle-plugin-0.1.18.jar",
          "size": 474152,
          "sha512": "86ebbcc96a709ad54c9719b4ffbaed011e8c6a9886f475c96639f02e95d4e64b439ac3399b0e3a2877828e9fcb5daa62316827cd4a023f27b854c8588a6af72d",
          "sha256": "63ff2ebf034c934963239d7d1cd596f19e477333471da78bf0014f2ec343941d",
          "sha1": "7ffb709120d6ded7dd68c90066078c811d79d83b",
          "md5": "622d514e6666af8329b1d4bbe30722db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.thetransactioncompany",
          "module": "jsonrpc2-client",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.18.jar",
          "url": "gradle-plugin-0.1.18.jar",
          "size": 474152,
          "sha512": "86ebbcc96a709ad54c9719b4ffbaed011e8c6a9886f475c96639f02e95d4e64b439ac3399b0e3a2877828e9fcb5daa62316827cd4a023f27b854c8588a6af72d",
          "sha256": "63ff2ebf034c934963239d7d1cd596f19e477333471da78bf0014f2ec343941d",
          "sha1": "7ffb709120d6ded7dd68c90066078c811d79d83b",
          "md5": "622d514e6666af8329b1d4bbe30722db"
        }
      ]
    }
  ]
}
