{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle-plugin",
    "version": "0.1.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.29.jar",
          "url": "gradle-plugin-0.1.29.jar",
          "size": 568174,
          "sha512": "303c086d4b96cf7a13fbceb95f7ebb67ff95ef233bdc536b97c920026488974424d932a0652df854c9fc965d027393a6cf84688bcbdf57a00f65ef830002ce9b",
          "sha256": "23eb054bbbfc924a514bdfb26748fa3cc51aaf07c57b3d7793752c2106e10024",
          "sha1": "b380a79923eac583952029c7f372bbab3eed8bc7",
          "md5": "a6a9a782a050a9939a186cc979d5f5d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.thetransactioncompany",
          "module": "jsonrpc2-client",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-0.1.29.jar",
          "url": "gradle-plugin-0.1.29.jar",
          "size": 568174,
          "sha512": "303c086d4b96cf7a13fbceb95f7ebb67ff95ef233bdc536b97c920026488974424d932a0652df854c9fc965d027393a6cf84688bcbdf57a00f65ef830002ce9b",
          "sha256": "23eb054bbbfc924a514bdfb26748fa3cc51aaf07c57b3d7793752c2106e10024",
          "sha1": "b380a79923eac583952029c7f372bbab3eed8bc7",
          "md5": "a6a9a782a050a9939a186cc979d5f5d6"
        }
      ]
    }
  ]
}
